### ISSUE TITLE
StructOpt Skip over troubled VASP jobs

### ISSUE THREAD

**Issue by akacz** [uw-cmg/MAST#419]
If one VASP job fails to converge after multiple runs, we need to prevent entire generation from being held up.

**Comment by thardaway1** [comment]
In this case I forced output files (OUTCAR and OSZICAR) to be replaced with "Bad Fitness", when VASP job fails to converges for 'n' number of times. This is a temporary/easy solution, but I think this could be a flexible solution, if user is allowed to set 'n' in the input file.

**Comment by cmgtam** [comment]
Will not fix: all future StructOpt development is being handled at https://github.com/uw-cmg/StructOpt_modular.
Closing this issue, since it only applies to MAST/StructOpt integration, and MAST and StructOpt are being decoupled (MAST will no longer be managing StructOpt in the newer versions; StructOpt may or may not decide to call MAST).
